dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

networks:
  rinkeby:
    priceFeed: ${RINKEBY_PRICE_FEED}
    verify: true
  development:
    verify: false
  ganache-local:
    verify: false

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
